### ISSUE TITLE
Error during running

### ISSUE THREAD

**Issue by jhonbgjmch** [Halvee/SNPfold#1]
root@ubuntu-VirtualBox:/home/ubuntu/Downloads/SNPfold-master# ls
accurate_p_value_comboSNPs.sh  estimate_p_value.sh  Readme.txt   SNPfold.py
accurate_p_value.sh            license.txt          ref_files
average_changes.txt            output               running.txt
root@ubuntu-VirtualBox:/home/ubuntu/Downloads/SNPfold-master# ./SNPfold.py
bash: ./SNPfold.py: Permission denied
root@ubuntu-VirtualBox:/home/ubuntu/Downloads/SNPfold-master# chmod a+x SNPfold.py 
root@ubuntu-VirtualBox:/home/ubuntu/Downloads/SNPfold-master# ./SNPfold.py 
./SNPfold.py: line 22: 
Matt Halvorsen (Original code, definition packaging/annotating 12-15-2010)	mhalvors@email.unc.edu
		 Sam Broadaway  (Modifications)
		 J.S. Martin	(Modifications 2010-07-12)
		 Chas Kissick	(Modifications 2011-10-05)	chas.kissick@gmail.com
: No such file or directory
import-im6.q16: not authorized `getopt' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `os' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `string' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `sys' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `math' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `numpy' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `random' @ error/constitute.c/WriteImage/1037.
from: can't read /var/mail/shutil
import-im6.q16: not authorized `datetime' @ error/constitute.c/WriteImage/1037.
./SNPfold.py: line 36: syntax error near unexpected token `('

**Comment by Halvee** [comment]
I added a shebang to the top of SNPfold.py and made it executable, so this issue should be resolved.
